[project]
name = "playwright-automation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mitmproxy>=12.2.1",
    "playwright>=1.58.0",
    "psycopg2-binary>=2.9.11",
    "pytest-playwright>=0.7.2",
]
